-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.material
(
    material_id serial NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    width double precision,
    height double precision,
    amount integer NOT NULL,
    price double precision NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    unit character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT material_pkey PRIMARY KEY (material_id)
    );

CREATE TABLE IF NOT EXISTS public."order"
(
    order_id serial NOT NULL,
    total_price double precision NOT NULL,
    status boolean NOT NULL,
    height double precision,
    width double precision,
    length double precision,
    date date NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT order_pkey PRIMARY KEY (order_id)
    );

CREATE TABLE IF NOT EXISTS public.order_item
(
    order_item_id serial NOT NULL,
    variant_id integer NOT NULL,
    request_description character varying COLLATE pg_catalog."default" NOT NULL,
    order_id integer,
    CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id)
    );

CREATE TABLE IF NOT EXISTS public.users
(
    users_id serial NOT NULL,
    user_name character varying COLLATE pg_catalog."default" NOT NULL,
    user_password character varying COLLATE pg_catalog."default" NOT NULL,
    user_email character varying COLLATE pg_catalog."default" NOT NULL,
    user_zipcode bigint NOT NULL,
    user_role character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (users_id)
    );

CREATE TABLE IF NOT EXISTS public.variant
(
    variant_id serial NOT NULL,
    material_id integer NOT NULL,
    length integer NOT NULL,
    CONSTRAINT variant_pkey PRIMARY KEY (variant_id)
    );

CREATE TABLE IF NOT EXISTS public.zip_code
(
    zip_code bigint NOT NULL,
    city character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT zip_code_pkey PRIMARY KEY (zip_code)
    );

ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (users_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_item
    ADD CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public."order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_item
    ADD CONSTRAINT order_item_variant_id_fkey FOREIGN KEY (variant_id)
    REFERENCES public.variant (variant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (user_zipcode)
    REFERENCES public.zip_code (zip_code) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.variant
    ADD CONSTRAINT variant_material_id_fkey FOREIGN KEY (material_id)
    REFERENCES public.material (material_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

INSERT INTO public.zip_code (zip_code, city)
VALUES
    ('2630', 'Taastrup'),
    ('1000', 'Copenhagen'),
    ('4000', 'Roskilde'),
    ('3400', 'Hillerød'),
    ('4600', 'Køge'),
    ('4700', 'Næstved'),
    ('4200', 'Slagelse'),
    ('4300', 'Holbæk'),
    ('4100', 'Ringsted'),
    ('4760', 'Vordingborg'),
    ('2670', 'Greve'),
    ('4330', 'Hvalsø'),
    ('2680', 'Solrød Strand'),
    ('5800', 'Nyborg'),
    ('4500', 'Nykøbing Sjælland'),
    ('2100', 'København'),
    ('3000', 'Helsingør'),
    ('4690', 'Haslev'),
    ('4400', 'Kalundborg'),
    ('4771', 'Kalvehave'),
    ('4173', 'Fjenneslev'),
    ('4684', 'Holme-Olstrup'),
    ('4180', 'Sorø'),
    ('4230', 'Skælskør'),
    ('4571', 'Grevinge'),
    ('4660', 'Store Heddinge'),
    ('4652', 'Hårlev'),
    ('4720', 'Præstø'),
    ('4632', 'Bjæverskov'),
    ('4750', 'Lundby'),
    ('4640', 'Faxe'),
    ('4653', 'Karise'),
    ('4220', 'Korsør'),
    ('4736', 'Karrebæksminde'),
    ('4671', 'Strøby'),
    ('4673', 'Rødvig Stevns');

    INSERT INTO public.users(user_name, user_password, user_email, user_zipcode, user_role, user_address)
    VALUES
        ('chad', '1234', 'chad@outlook.com' '2500', 'admin', 'Allégade 22'),
        ('hulk', '1234', 'hulk@smash.now' '2630', 'user', 'Avengers HQ'),
        ('jeff', 'jeff123', 'jeff@mynameis.com' '8000', 'user', '22 Jump Street');




    END;