-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    user_name character varying NOT NULL,
    "user_password " character varying NOT NULL,
    user_email character varying NOT NULL,
    user_zipcode bigint NOT NULL,
    user_role character varying NOT NULL,
    user_address character varying NOT NULL,
    PRIMARY KEY (user_id)
    );

CREATE TABLE IF NOT EXISTS public.zip_code
(
    zip_code bigint NOT NULL,
    city character varying NOT NULL,
    PRIMARY KEY (zip_code)
    );

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    carport_width double precision NOT NULL,
    carport_length double precision NOT NULL,
    date date NOT NULL,
    status integer NOT NULL,
    user_id integer NOT NULL,
    total_price double precision NOT NULL,
    PRIMARY KEY (order_id)
    );

ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (user_zipcode)
    REFERENCES public.zip_code (zip_code) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;