@startuml
'https://plantuml.com/state-diagram

scale 350 width

[*] --> FOG : Googling "FOG Carport"

state FOG {
  FOG --> IndexPage: Google : Fog carport
  IndexPage --> LoginPage : From the "frontPage" you have a "login" button
  LoginPage --> EnterLogInInfo: if you have an account
  LoginPage --> SignUp: if you dont have an account

  SignUp --> IndexPage: after createing an account, back to index
  EnterLogInInfo --> IndexPage: after "loggin in" back to index




  state Admin {

    IndexPage --> Order: if logged-in into a "admin-account", have the option to go to Order

    Order --> RequestSystem: clicking "Order" takes you to the requestSystem

    RequestSystem --> HelpWithBuildsAndCarportMeasurement: can click on a request and get more details

    HelpWithBuildsAndCarportMeasurement --> SendOfferToUser: admin can "change" pris and measurment on the carport if need be

    SendOfferToUser --> [*]: after helping, send an offer to customer and program ends
  }
}

@enduml
